GET http://127.0.0.1:8000/ HTTP/1.1

###
GET http://127.0.0.1:8000/sentiment/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NDkzMjM0LCJpYXQiOjE3NDU0OTI5MzQsImp0aSI6ImYwNzIwODEzYzAwZjQ3NmE5NWIxMThmYTViYzU2NDFmIiwidXNlcl9pZCI6MX0.AJtNRlLL6r4L3PBIBPmMDXNwlsHteHS4ScZY4dmztcU

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username":"neesa",
    "password":"023015"
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"023015"
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username":"test",
    "password":"023015"
}


