# Generated by Django 5.2.1 on 2025-05-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
