# Generated by Django 5.2.1 on 2025-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_like_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspost",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=500),
        ),
    ]
