# Generated by Django 5.2.1 on 2025-05-14 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
