# Generated by Django 5.2.1 on 2025-05-25 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_newspost_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="is_liked",
        ),
    ]
