# Generated by Django 5.2.1 on 2025-06-01 07:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_customtag_taggednewspost_alter_newspost_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspost",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
