# Generated by Django 5.2.1 on 2025-06-01 10:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_newspost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspost",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
