# Generated by Django 5.2.1 on 2025-06-02 08:04

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_newspost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspost",
            name="description",
            field=tinymce.models.HTMLField(default="h"),
            preserve_default=False,
        ),
    ]
