# Generated by Django 5.2.1 on 2025-06-18 11:41

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_alter_newspost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="news.comment",
            ),
        ),
    ]
