# Generated by Django 5.1.7 on 2025-04-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockNewsURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="NewsURLRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.CharField(blank=True, max_length=100, null=True)),
                ("search_bar", models.CharField(blank=True, max_length=100, null=True)),
                ("main_div", models.CharField(blank=True, max_length=100, null=True)),
                ("div_list", models.CharField(blank=True, max_length=100, null=True)),
                ("link_text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_rules",
                        to="dashboard.newsurl",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockNewsURLRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_div", models.CharField(max_length=50)),
                ("tbody", models.CharField(max_length=50)),
                ("rows", models.CharField(max_length=50)),
                ("p_element", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="dashboard.stocknewsurl",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=500)),
                (
                    "symbol",
                    models.ManyToManyField(
                        related_name="symbol", to="dashboard.symbol"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SymbolKeywordRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keywords",
                    models.ManyToManyField(
                        related_name="news_keywords", to="dashboard.keyword"
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_symbols",
                        to="dashboard.symbol",
                    ),
                ),
            ],
        ),
    ]
