# Generated by Django 5.1.7 on 2025-04-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolkeywordrelation',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='symbolkeywordrelation',
            name='symbol',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='SymbolKeywordRelation',
        ),
    ]
