# Generated by Django 5.1.7 on 2025-04-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_stocknewsurlrule_click_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknewsurlrule',
            name='click_button',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
