# Generated by Django 5.1.7 on 2025-04-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_alter_stocknewsurlrule_click_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknewsurlrule",
            name="headline",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stocknewsurlrule",
            name="summary_class",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stocknewsurlrule",
            name="summary_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
