# Generated by Django 5.1.7 on 2025-04-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_stocknewsurlrule_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
