# Generated by Django 5.1.7 on 2025-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_stockrecord_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsurlrule",
            name="link_text",
        ),
        migrations.RemoveField(
            model_name="stocknewsurlrule",
            name="p_element",
        ),
        migrations.AddField(
            model_name="newsurlrule",
            name="headline",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="newsurlrule",
            name="summary_class",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="newsurlrule",
            name="summary_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
