# Generated by Django 5.1.7 on 2025-04-06 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_remove_newsurlrule_link_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsurlrule",
            name="summary_id",
        ),
    ]
