# Generated by Django 5.1.7 on 2025-04-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_remove_newsurlrule_summary_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbolkeywordrelation",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="news_keywords",
                to="dashboard.keyword",
            ),
        ),
    ]
