# Generated by Django 5.1.7 on 2025-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_squashed_0014_alter_symbolkeywordrelation_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknewsurlrule",
            name="uploaded",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="date",
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
    ]
