# Generated by Django 5.1.7 on 2025-04-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0015_stocknewsurlrule_uploaded_stockrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockrecord",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
