# Generated by Django 5.1.7 on 2025-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0016_alter_stockrecord_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknewsurlrule",
            name="datexpath",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
