# Generated by Django 5.2.1 on 2025-05-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="support",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
