# Generated by Django 5.2.1 on 2025-05-20 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("scraper", "0001_initial"),
        ("scraper", "0002_alter_news_status"),
        ("scraper", "0003_announcement"),
        ("scraper", "0004_alter_category_options_alter_news_options_and_more"),
        ("scraper", "0005_remove_news_created_by_remove_news_updated_by_and_more"),
        ("scraper", "0006_remove_news_category_remove_news_creator_and_more"),
        ("scraper", "0007_announcement_tags"),
        ("scraper", "0008_newsurl_alter_announcement_tags_newsurlrule"),
        ("scraper", "0009_newsurlrule_headline_newsurlrule_summary_id"),
        ("scraper", "0010_rename_summary_id_newsurlrule_summary"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=225, unique=True)),
                ("sector", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockNewsURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
            ],
            options={
                "verbose_name": "StockNews URL",
                "verbose_name_plural": "StockNews URLs",
            },
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectortype",
                        to="scraper.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("url", models.URLField(max_length=500)),
                ("announcement", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockNewsURLRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "click_button",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("main_div", models.CharField(blank=True, max_length=50, null=True)),
                ("div_list", models.CharField(blank=True, max_length=100, null=True)),
                ("tbody", models.CharField(blank=True, max_length=50, null=True)),
                ("rows", models.CharField(blank=True, max_length=50, null=True)),
                ("uploaded", models.CharField(blank=True, max_length=50, null=True)),
                ("headline", models.CharField(blank=True, max_length=50, null=True)),
                ("summary_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "summary_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="scraper.stocknewsurl",
                    ),
                ),
            ],
            options={
                "verbose_name": "StockNews URL Rule",
                "verbose_name_plural": "StockNews URL Rules",
            },
        ),
        migrations.CreateModel(
            name="StockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True, null=True)),
                ("url", models.URLField(max_length=500)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "keywords",
                    models.ManyToManyField(
                        blank=True, related_name="keywords", to="scraper.keyword"
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbol",
                        to="scraper.symbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Record",
                "verbose_name_plural": "Stock Records",
            },
        ),
        migrations.CreateModel(
            name="NewsURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsURLRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.CharField(blank=True, max_length=100, null=True)),
                ("search_bar", models.CharField(blank=True, max_length=100, null=True)),
                ("main_div", models.CharField(blank=True, max_length=100, null=True)),
                ("div_list", models.CharField(blank=True, max_length=100, null=True)),
                ("link_text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_rules",
                        to="scraper.newsurl",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=50, null=True)),
                ("summary", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
