# Generated by Django 5.1.7 on 2025-05-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
