# Generated by Django 5.1.7 on 2025-05-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0002_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="records", to="scraper.keyword"
            ),
        ),
    ]
