# Generated by Django 5.1.7 on 2025-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0002_alter_news_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("url", models.URLField(max_length=500)),
                ("announcement", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
