# Generated by Django 5.1.7 on 2025-05-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0003_stockrecord_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockrecord",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="keywords", to="scraper.keyword"
            ),
        ),
    ]
