# Generated by Django 5.2.1 on 2025-05-13 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0003_announcement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "News", "verbose_name_plural": "News"},
        ),
        migrations.AlterModelOptions(
            name="stocknewsurl",
            options={
                "verbose_name": "StockNews URL",
                "verbose_name_plural": "StockNews URLs",
            },
        ),
        migrations.AlterModelOptions(
            name="stocknewsurlrule",
            options={
                "verbose_name": "StockNews URL Rule",
                "verbose_name_plural": "StockNews URL Rules",
            },
        ),
        migrations.AlterModelOptions(
            name="stockrecord",
            options={
                "verbose_name": "Stock Record",
                "verbose_name_plural": "Stock Records",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
