# Generated by Django 5.2.1 on 2025-05-13 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0004_alter_category_options_alter_news_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="news",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="news",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
