# Generated by Django 5.1.7 on 2025-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0004_alter_stockrecord_keywords"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
