# Generated by Django 5.2.1 on 2025-05-13 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0005_remove_news_created_by_remove_news_updated_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="category",
        ),
        migrations.RemoveField(
            model_name="news",
            name="creator",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="News",
        ),
    ]
