# Generated by Django 5.1.7 on 2025-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0006_news_created_at_news_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
