# Generated by Django 5.2.1 on 2025-05-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0006_remove_news_category_remove_news_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="tags",
            field=models.CharField(default="news", max_length=255),
            preserve_default=False,
        ),
    ]
