# Generated by Django 5.2.1 on 2025-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_emailnotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotification",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-01-02"),
            preserve_default=False,
        ),
    ]
