# Generated by Django 5.2.1 on 2025-05-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_emailnotification_sent_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailnotification",
            old_name="sent_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="emailnotification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
